### ISSUE TITLE
Issue when encoding LogicalTypes::TimestampMillis

### ISSUE THREAD

**Issue by stefanste** [salsify/avro-patches#13]
Hello,

I've encountered an issue with encoding and the timestamp-millis logical type - when we use that logical type, throughout our codebase we've already converted the underlying Time or DateTime value to a Numeric, so it fails when trying to call `to_time` on it when encoding: https://github.com/salsify/avro-patches/blob/master/lib/avro-patches/logical_types/logical_types.rb#L19

Would it be possible to add a guard in this encode method which just returns the value itself if it is already 'encoded'? Something like:

```
module Avro
  module LogicalTypes
    module TimestampMillis
      def self.encode(value)
        return value if value.kind_of?(Numeric)

        time = value.to_time
        time.to_i * 1000 + time.usec / 1000
      end
    end
  end
end
```

Cheers,
Stefan

**Comment by tjwp** [comment]
Sorry it has taken a while to respond here. That looks reasonable to me. I'll try to add something in the near future. Or would like to open a PR?

**Comment by tjwp** [comment]
I've opened https://github.com/salsify/avro-patches/pull/18

**Comment by stefanste** [comment]
Ah great, thank you very much!
