### ISSUE TITLE
schema validator does not handle Unions correctly

### ISSUE THREAD

**Issue by GrafBlutwurst** [salsify/avro-patches#21]
As per Avro specification:
https://avro.apache.org/docs/1.8.2/spec.html#json_encoding

unions in json-format records should be encoded as a single object containing a single property where its name should be the tag-type refering to the union definition and its value being of that type.

Currently `validate_union` just iterates through all member types and uses the first that fits.

given the following schema

``` 
{
    "type":"record",
    "name":"ShouldSucceed",
    "namespace":"com.scigility.schemadrivenload",
    "fields":[
        {"name":"a","type":"int"},
        {"name":"b","type":"string"},
        {"name":"c","type":"boolean"},
        {"name":"d","type":["null","string"]}
    ]
}
```

this should be valid:

`{"a":1,"b":"","c":true,"d":{"string":""}} `

but leads to an error
>at .d expected union of ['null', 'string'], got record with value {"string"=>""}

whereas

`{"a":1,"b":"","c":true,"d":"asdf"} `

should be rejected but isn't.

**Comment by tjwp** [comment]
Hi @GrafBlutwurst,

Thank you for raising this issue.

I don't believe that the ruby implementation of avro supports JSON encoding/decoding (although it would be nice if it did).

The schema validator is expected to be called with a datum, not an encoded value. 

For the JSON encoded example that you provided: `{"a":1,"b":"","c":true,"d":{"string":""}}`

I would expect a decoder to return a datum that would be represented in ruby as the hash:
`{ "a" => 1, "b" => "", "c" => true, "d" => "" }`

And the schema validator would consider that valid.

**Comment by GrafBlutwurst** [comment]
EDIT: Misread I understand what you mean. My bad.

~~I would expect the same but I don't think that is the case due to the fact on how unions are handled in the current code. pinging @bpreis to confirm~~

~~If I remember correctly union decoding just goes in order through the union members and tries to decode the value in turn using the current member.~~

~~See github.com/salsify/avro-patches/blob/fe7210574b3a8157be030b7054c2f414e9ec1550/lib/avro-patches/schema_validator/schema_validator.rb#L176~~

~~I don't think that is the correct logic as a union should be represented in a datum as an object with a single member where the property name represents the union tag and the value it's according json-value representation.~~
